/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : Id,
  'title' : string,
  'activityType' : ActivityType,
  'contactName' : string,
  'createdAt' : bigint,
  'description' : string,
  'dealId' : Id,
  'tenantId' : Id,
  'occurredAt' : bigint,
  'companyName' : string,
  'contactId' : Id,
  'dealName' : string,
  'companyId' : Id,
}
export interface ActivityInput {
  'title' : string,
  'activityType' : ActivityType,
  'contactName' : string,
  'description' : string,
  'dealId' : Id,
  'occurredAt' : bigint,
  'companyName' : string,
  'contactId' : Id,
  'dealName' : string,
  'companyId' : Id,
}
export type ActivityType = { 'Email' : null } |
  { 'Call' : null } |
  { 'Note' : null } |
  { 'Meeting' : null };
export interface Company {
  'id' : Id,
  'name' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'website' : string,
  'tenantId' : Id,
  'address' : string,
  'notes' : string,
  'phone' : string,
  'industry' : string,
}
export interface CompanyInput {
  'name' : string,
  'tags' : Array<string>,
  'website' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
  'industry' : string,
}
export interface Contact {
  'id' : Id,
  'linkedIn' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'tags' : Array<string>,
  'email' : string,
  'tenantId' : Id,
  'updatedAt' : bigint,
  'company' : string,
  'notes' : string,
  'phone' : string,
  'companyId' : string,
}
export interface ContactInput {
  'linkedIn' : string,
  'name' : string,
  'role' : string,
  'tags' : Array<string>,
  'email' : string,
  'company' : string,
  'notes' : string,
  'phone' : string,
  'companyId' : string,
}
export interface Deal {
  'id' : Id,
  'nextActivityDate' : [] | [bigint],
  'title' : string,
  'nextActivityNote' : string,
  'nextActivityType' : [] | [ActivityType],
  'contactName' : string,
  'value' : number,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'tenantId' : Id,
  'updatedAt' : bigint,
  'stage' : Stage,
  'notes' : string,
  'companyName' : string,
  'contactId' : Id,
  'companyId' : Id,
}
export interface DealInput {
  'nextActivityDate' : [] | [bigint],
  'title' : string,
  'nextActivityNote' : string,
  'nextActivityType' : [] | [ActivityType],
  'contactName' : string,
  'value' : number,
  'tags' : Array<string>,
  'stage' : Stage,
  'notes' : string,
  'companyName' : string,
  'contactId' : Id,
  'companyId' : Id,
}
export interface DealNextActivityInput {
  'activityType' : [] | [ActivityType],
  'date' : [] | [bigint],
  'note' : string,
}
export type Id = string;
export type Stage = { 'Lead' : null } |
  { 'Qualified' : null } |
  { 'Proposal' : null } |
  { 'Negotiation' : null } |
  { 'ClosedWon' : null } |
  { 'ClosedLost' : null };
export interface Task {
  'id' : Id,
  'title' : string,
  'contactName' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : string,
  'dealId' : Id,
  'tenantId' : Id,
  'contactId' : Id,
  'dealName' : string,
}
export interface TaskInput {
  'title' : string,
  'contactName' : string,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : string,
  'dealId' : Id,
  'contactId' : Id,
  'dealName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createActivity' : ActorMethod<[ActivityInput], string>,
  'createCompany' : ActorMethod<[CompanyInput], string>,
  'createContact' : ActorMethod<[ContactInput], string>,
  'createDeal' : ActorMethod<[DealInput], string>,
  'createTask' : ActorMethod<[TaskInput], string>,
  'deleteActivity' : ActorMethod<[string], undefined>,
  'deleteCompany' : ActorMethod<[string], undefined>,
  'deleteContact' : ActorMethod<[string], undefined>,
  'deleteDeal' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getActivity' : ActorMethod<[string], Activity>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompany' : ActorMethod<[string], Company>,
  'getContact' : ActorMethod<[string], Contact>,
  'getDeal' : ActorMethod<[string], Deal>,
  'getTask' : ActorMethod<[string], Task>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivities' : ActorMethod<[], Array<Activity>>,
  'listActivitiesByCompany' : ActorMethod<[string], Array<Activity>>,
  'listActivitiesByContact' : ActorMethod<[string], Array<Activity>>,
  'listActivitiesByDeal' : ActorMethod<[string], Array<Activity>>,
  'listCompanies' : ActorMethod<[], Array<Company>>,
  'listContacts' : ActorMethod<[], Array<Contact>>,
  'listDeals' : ActorMethod<[], Array<Deal>>,
  'listDealsByStage' : ActorMethod<[Stage], Array<Deal>>,
  'listTasks' : ActorMethod<[], Array<Task>>,
  'listTasksByCompleted' : ActorMethod<[boolean], Array<Task>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCompanies' : ActorMethod<[string], Array<Company>>,
  'searchContacts' : ActorMethod<[string], Array<Contact>>,
  'searchDeals' : ActorMethod<[string], Array<Deal>>,
  'setDealNextActivity' : ActorMethod<
    [string, DealNextActivityInput],
    undefined
  >,
  'updateActivity' : ActorMethod<[string, ActivityInput], undefined>,
  'updateCompany' : ActorMethod<[string, CompanyInput], undefined>,
  'updateContact' : ActorMethod<[string, ContactInput], undefined>,
  'updateDeal' : ActorMethod<[string, DealInput], undefined>,
  'updateTask' : ActorMethod<[string, TaskInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];