/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityType = IDL.Variant({
  'Email' : IDL.Null,
  'Call' : IDL.Null,
  'Note' : IDL.Null,
  'Meeting' : IDL.Null,
});
export const Id = IDL.Text;
export const ActivityInput = IDL.Record({
  'title' : IDL.Text,
  'activityType' : ActivityType,
  'contactName' : IDL.Text,
  'description' : IDL.Text,
  'dealId' : Id,
  'occurredAt' : IDL.Int,
  'companyName' : IDL.Text,
  'contactId' : Id,
  'dealName' : IDL.Text,
  'companyId' : Id,
});
export const CompanyInput = IDL.Record({
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'website' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'industry' : IDL.Text,
});
export const ContactInput = IDL.Record({
  'linkedIn' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'companyId' : IDL.Text,
});
export const Stage = IDL.Variant({
  'Lead' : IDL.Null,
  'Qualified' : IDL.Null,
  'Proposal' : IDL.Null,
  'ClosedWon' : IDL.Null,
  'ClosedLost' : IDL.Null,
});
export const DealInput = IDL.Record({
  'nextActivityDate' : IDL.Opt(IDL.Int),
  'title' : IDL.Text,
  'nextActivityNote' : IDL.Text,
  'nextActivityType' : IDL.Opt(ActivityType),
  'contactName' : IDL.Text,
  'value' : IDL.Float64,
  'tags' : IDL.Vec(IDL.Text),
  'stage' : Stage,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'contactId' : Id,
  'companyId' : Id,
});
export const TaskInput = IDL.Record({
  'title' : IDL.Text,
  'contactName' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'dealId' : Id,
  'contactId' : Id,
  'dealName' : IDL.Text,
});
export const Activity = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'activityType' : ActivityType,
  'contactName' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'dealId' : Id,
  'tenantId' : Id,
  'occurredAt' : IDL.Int,
  'companyName' : IDL.Text,
  'contactId' : Id,
  'dealName' : IDL.Text,
  'companyId' : Id,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Company = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'website' : IDL.Text,
  'tenantId' : Id,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'industry' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : Id,
  'linkedIn' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'tenantId' : Id,
  'updatedAt' : IDL.Int,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'companyId' : IDL.Text,
});
export const Deal = IDL.Record({
  'id' : Id,
  'nextActivityDate' : IDL.Opt(IDL.Int),
  'title' : IDL.Text,
  'nextActivityNote' : IDL.Text,
  'nextActivityType' : IDL.Opt(ActivityType),
  'contactName' : IDL.Text,
  'value' : IDL.Float64,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'tenantId' : Id,
  'updatedAt' : IDL.Int,
  'stage' : Stage,
  'notes' : IDL.Text,
  'companyName' : IDL.Text,
  'contactId' : Id,
  'companyId' : Id,
});
export const Task = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'contactName' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'dealId' : Id,
  'tenantId' : Id,
  'contactId' : Id,
  'dealName' : IDL.Text,
});
export const DealNextActivityInput = IDL.Record({
  'activityType' : IDL.Opt(ActivityType),
  'date' : IDL.Opt(IDL.Int),
  'note' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createActivity' : IDL.Func([ActivityInput], [IDL.Text], []),
  'createCompany' : IDL.Func([CompanyInput], [IDL.Text], []),
  'createContact' : IDL.Func([ContactInput], [IDL.Text], []),
  'createDeal' : IDL.Func([DealInput], [IDL.Text], []),
  'createTask' : IDL.Func([TaskInput], [IDL.Text], []),
  'deleteActivity' : IDL.Func([IDL.Text], [], []),
  'deleteCompany' : IDL.Func([IDL.Text], [], []),
  'deleteContact' : IDL.Func([IDL.Text], [], []),
  'deleteDeal' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getActivity' : IDL.Func([IDL.Text], [Activity], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompany' : IDL.Func([IDL.Text], [Company], ['query']),
  'getContact' : IDL.Func([IDL.Text], [Contact], ['query']),
  'getDeal' : IDL.Func([IDL.Text], [Deal], ['query']),
  'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'listActivitiesByCompany' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'listActivitiesByContact' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'listActivitiesByDeal' : IDL.Func([IDL.Text], [IDL.Vec(Activity)], ['query']),
  'listCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'listDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'listDealsByStage' : IDL.Func([Stage], [IDL.Vec(Deal)], ['query']),
  'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'listTasksByCompleted' : IDL.Func([IDL.Bool], [IDL.Vec(Task)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCompanies' : IDL.Func([IDL.Text], [IDL.Vec(Company)], ['query']),
  'searchContacts' : IDL.Func([IDL.Text], [IDL.Vec(Contact)], ['query']),
  'searchDeals' : IDL.Func([IDL.Text], [IDL.Vec(Deal)], ['query']),
  'setDealNextActivity' : IDL.Func([IDL.Text, DealNextActivityInput], [], []),
  'updateActivity' : IDL.Func([IDL.Text, ActivityInput], [], []),
  'updateCompany' : IDL.Func([IDL.Text, CompanyInput], [], []),
  'updateContact' : IDL.Func([IDL.Text, ContactInput], [], []),
  'updateDeal' : IDL.Func([IDL.Text, DealInput], [], []),
  'updateTask' : IDL.Func([IDL.Text, TaskInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityType = IDL.Variant({
    'Email' : IDL.Null,
    'Call' : IDL.Null,
    'Note' : IDL.Null,
    'Meeting' : IDL.Null,
  });
  const Id = IDL.Text;
  const ActivityInput = IDL.Record({
    'title' : IDL.Text,
    'activityType' : ActivityType,
    'contactName' : IDL.Text,
    'description' : IDL.Text,
    'dealId' : Id,
    'occurredAt' : IDL.Int,
    'companyName' : IDL.Text,
    'contactId' : Id,
    'dealName' : IDL.Text,
    'companyId' : Id,
  });
  const CompanyInput = IDL.Record({
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'website' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'industry' : IDL.Text,
  });
  const ContactInput = IDL.Record({
    'linkedIn' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const Stage = IDL.Variant({
    'Lead' : IDL.Null,
    'Qualified' : IDL.Null,
    'Proposal' : IDL.Null,
    'ClosedWon' : IDL.Null,
    'ClosedLost' : IDL.Null,
  });
  const DealInput = IDL.Record({
    'nextActivityDate' : IDL.Opt(IDL.Int),
    'title' : IDL.Text,
    'nextActivityNote' : IDL.Text,
    'nextActivityType' : IDL.Opt(ActivityType),
    'contactName' : IDL.Text,
    'value' : IDL.Float64,
    'tags' : IDL.Vec(IDL.Text),
    'stage' : Stage,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'contactId' : Id,
    'companyId' : Id,
  });
  const TaskInput = IDL.Record({
    'title' : IDL.Text,
    'contactName' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'dealId' : Id,
    'contactId' : Id,
    'dealName' : IDL.Text,
  });
  const Activity = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'activityType' : ActivityType,
    'contactName' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'dealId' : Id,
    'tenantId' : Id,
    'occurredAt' : IDL.Int,
    'companyName' : IDL.Text,
    'contactId' : Id,
    'dealName' : IDL.Text,
    'companyId' : Id,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Company = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'website' : IDL.Text,
    'tenantId' : Id,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'industry' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : Id,
    'linkedIn' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'tenantId' : Id,
    'updatedAt' : IDL.Int,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const Deal = IDL.Record({
    'id' : Id,
    'nextActivityDate' : IDL.Opt(IDL.Int),
    'title' : IDL.Text,
    'nextActivityNote' : IDL.Text,
    'nextActivityType' : IDL.Opt(ActivityType),
    'contactName' : IDL.Text,
    'value' : IDL.Float64,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'tenantId' : Id,
    'updatedAt' : IDL.Int,
    'stage' : Stage,
    'notes' : IDL.Text,
    'companyName' : IDL.Text,
    'contactId' : Id,
    'companyId' : Id,
  });
  const Task = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'contactName' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'dealId' : Id,
    'tenantId' : Id,
    'contactId' : Id,
    'dealName' : IDL.Text,
  });
  const DealNextActivityInput = IDL.Record({
    'activityType' : IDL.Opt(ActivityType),
    'date' : IDL.Opt(IDL.Int),
    'note' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createActivity' : IDL.Func([ActivityInput], [IDL.Text], []),
    'createCompany' : IDL.Func([CompanyInput], [IDL.Text], []),
    'createContact' : IDL.Func([ContactInput], [IDL.Text], []),
    'createDeal' : IDL.Func([DealInput], [IDL.Text], []),
    'createTask' : IDL.Func([TaskInput], [IDL.Text], []),
    'deleteActivity' : IDL.Func([IDL.Text], [], []),
    'deleteCompany' : IDL.Func([IDL.Text], [], []),
    'deleteContact' : IDL.Func([IDL.Text], [], []),
    'deleteDeal' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getActivity' : IDL.Func([IDL.Text], [Activity], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompany' : IDL.Func([IDL.Text], [Company], ['query']),
    'getContact' : IDL.Func([IDL.Text], [Contact], ['query']),
    'getDeal' : IDL.Func([IDL.Text], [Deal], ['query']),
    'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'listActivitiesByCompany' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'listActivitiesByContact' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'listActivitiesByDeal' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'listCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'listDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'listDealsByStage' : IDL.Func([Stage], [IDL.Vec(Deal)], ['query']),
    'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'listTasksByCompleted' : IDL.Func([IDL.Bool], [IDL.Vec(Task)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCompanies' : IDL.Func([IDL.Text], [IDL.Vec(Company)], ['query']),
    'searchContacts' : IDL.Func([IDL.Text], [IDL.Vec(Contact)], ['query']),
    'searchDeals' : IDL.Func([IDL.Text], [IDL.Vec(Deal)], ['query']),
    'setDealNextActivity' : IDL.Func([IDL.Text, DealNextActivityInput], [], []),
    'updateActivity' : IDL.Func([IDL.Text, ActivityInput], [], []),
    'updateCompany' : IDL.Func([IDL.Text, CompanyInput], [], []),
    'updateContact' : IDL.Func([IDL.Text, ContactInput], [], []),
    'updateDeal' : IDL.Func([IDL.Text, DealInput], [], []),
    'updateTask' : IDL.Func([IDL.Text, TaskInput], [], []),
    'vetkdPublicKey' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'vetkdDeriveKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Vec(IDL.Nat8)], []),
  });
};

export const init = ({ IDL }) => { return []; };