/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactInput {
    linkedIn: string;
    name: string;
    role: string;
    tags: Array<string>;
    email: string;
    company: string;
    notes: string;
    phone: string;
    companyId: string;
}
export interface Contact {
    id: Id;
    linkedIn: string;
    name: string;
    createdAt: bigint;
    role: string;
    tags: Array<string>;
    email: string;
    tenantId: Id;
    updatedAt: bigint;
    company: string;
    notes: string;
    phone: string;
    companyId: string;
}
export interface Task {
    id: Id;
    title: string;
    contactName: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    dealId: Id;
    tenantId: Id;
    contactId: Id;
    dealName: string;
}
export interface Company {
    id: Id;
    name: string;
    createdAt: bigint;
    tags: Array<string>;
    website: string;
    tenantId: Id;
    address: string;
    notes: string;
    phone: string;
    industry: string;
}
export interface TaskInput {
    title: string;
    contactName: string;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    dealId: Id;
    contactId: Id;
    dealName: string;
}
export interface Activity {
    id: Id;
    title: string;
    activityType: ActivityType;
    contactName: string;
    createdAt: bigint;
    description: string;
    dealId: Id;
    tenantId: Id;
    occurredAt: bigint;
    companyName: string;
    contactId: Id;
    dealName: string;
    companyId: Id;
}
export interface DealNextActivityInput {
    activityType?: ActivityType;
    date?: bigint;
    note: string;
}
export interface ActivityInput {
    title: string;
    activityType: ActivityType;
    contactName: string;
    description: string;
    dealId: Id;
    occurredAt: bigint;
    companyName: string;
    contactId: Id;
    dealName: string;
    companyId: Id;
}
export interface DealInput {
    nextActivityDate?: bigint;
    title: string;
    nextActivityNote: string;
    nextActivityType?: ActivityType;
    contactName: string;
    value: number;
    tags: Array<string>;
    stage: Stage;
    notes: string;
    companyName: string;
    contactId: Id;
    companyId: Id;
}
export type Id = string;
export interface Deal {
    id: Id;
    nextActivityDate?: bigint;
    title: string;
    nextActivityNote: string;
    nextActivityType?: ActivityType;
    contactName: string;
    value: number;
    createdAt: bigint;
    tags: Array<string>;
    tenantId: Id;
    updatedAt: bigint;
    stage: Stage;
    notes: string;
    companyName: string;
    contactId: Id;
    companyId: Id;
}
export interface CompanyInput {
    name: string;
    tags: Array<string>;
    website: string;
    address: string;
    notes: string;
    phone: string;
    industry: string;
}
export interface UserProfile {
    name: string;
}
export enum ActivityType {
    Email = "Email",
    Call = "Call",
    Note = "Note",
    Meeting = "Meeting"
}
export enum Stage {
    Lead = "Lead",
    Qualified = "Qualified",
    Proposal = "Proposal",
    ClosedWon = "ClosedWon",
    Negotiation = "Negotiation",
    ClosedLost = "ClosedLost"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createActivity(input: ActivityInput): Promise<string>;
    createCompany(input: CompanyInput): Promise<string>;
    createContact(input: ContactInput): Promise<string>;
    createDeal(input: DealInput): Promise<string>;
    createTask(input: TaskInput): Promise<string>;
    deleteActivity(id: string): Promise<void>;
    deleteCompany(id: string): Promise<void>;
    deleteContact(id: string): Promise<void>;
    deleteDeal(id: string): Promise<void>;
    deleteTask(id: string): Promise<void>;
    getActivity(id: string): Promise<Activity>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompany(id: string): Promise<Company>;
    getContact(id: string): Promise<Contact>;
    getDeal(id: string): Promise<Deal>;
    getTask(id: string): Promise<Task>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listActivities(): Promise<Array<Activity>>;
    listActivitiesByCompany(companyId: string): Promise<Array<Activity>>;
    listActivitiesByContact(contactId: string): Promise<Array<Activity>>;
    listActivitiesByDeal(dealId: string): Promise<Array<Activity>>;
    listCompanies(): Promise<Array<Company>>;
    listContacts(): Promise<Array<Contact>>;
    listDeals(): Promise<Array<Deal>>;
    listDealsByStage(stage: Stage): Promise<Array<Deal>>;
    listTasks(): Promise<Array<Task>>;
    listTasksByCompleted(completed: boolean): Promise<Array<Task>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCompanies(searchText: string): Promise<Array<Company>>;
    searchContacts(searchText: string): Promise<Array<Contact>>;
    searchDeals(searchText: string): Promise<Array<Deal>>;
    setDealNextActivity(id: string, input: DealNextActivityInput): Promise<void>;
    updateActivity(id: string, input: ActivityInput): Promise<void>;
    updateCompany(id: string, input: CompanyInput): Promise<void>;
    updateContact(id: string, input: ContactInput): Promise<void>;
    updateDeal(id: string, input: DealInput): Promise<void>;
    updateTask(id: string, input: TaskInput): Promise<void>;
}
import type { Activity as _Activity, ActivityInput as _ActivityInput, ActivityType as _ActivityType, Deal as _Deal, DealInput as _DealInput, DealNextActivityInput as _DealNextActivityInput, Id as _Id, Stage as _Stage, Task as _Task, TaskInput as _TaskInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createActivity(arg0: ActivityInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createActivity(to_candid_ActivityInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createActivity(to_candid_ActivityInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCompany(arg0: CompanyInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompany(arg0);
            return result;
        }
    }
    async createContact(arg0: ContactInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContact(arg0);
            return result;
        }
    }
    async createDeal(arg0: DealInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeal(to_candid_DealInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeal(to_candid_DealInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTask(arg0: TaskInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_TaskInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_TaskInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteActivity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0);
            return result;
        }
    }
    async deleteCompany(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCompany(arg0);
            return result;
        }
    }
    async deleteContact(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteDeal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeal(arg0);
            return result;
        }
    }
    async deleteTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getActivity(arg0: string): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivity(arg0);
                return from_candid_Activity_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivity(arg0);
            return from_candid_Activity_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompany(arg0: string): Promise<Company> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompany(arg0);
            return result;
        }
    }
    async getContact(arg0: string): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return result;
        }
    }
    async getDeal(arg0: string): Promise<Deal> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeal(arg0);
                return from_candid_Deal_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeal(arg0);
            return from_candid_Deal_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: string): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivities();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivities();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActivitiesByCompany(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivitiesByCompany(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivitiesByCompany(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActivitiesByContact(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivitiesByContact(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivitiesByContact(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActivitiesByDeal(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivitiesByDeal(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivitiesByDeal(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCompanies(): Promise<Array<Company>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCompanies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCompanies();
            return result;
        }
    }
    async listContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContacts();
            return result;
        }
    }
    async listDeals(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeals();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeals();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDealsByStage(arg0: Stage): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDealsByStage(to_candid_Stage_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDealsByStage(to_candid_Stage_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasks();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasks();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasksByCompleted(arg0: boolean): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasksByCompleted(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasksByCompleted(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchCompanies(arg0: string): Promise<Array<Company>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCompanies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCompanies(arg0);
            return result;
        }
    }
    async searchContacts(arg0: string): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchContacts(arg0);
            return result;
        }
    }
    async searchDeals(arg0: string): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDeals(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDeals(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDealNextActivity(arg0: string, arg1: DealNextActivityInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDealNextActivity(arg0, to_candid_DealNextActivityInput_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDealNextActivity(arg0, to_candid_DealNextActivityInput_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateActivity(arg0: string, arg1: ActivityInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, to_candid_ActivityInput_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, to_candid_ActivityInput_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCompany(arg0: string, arg1: CompanyInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompany(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompany(arg0, arg1);
            return result;
        }
    }
    async updateContact(arg0: string, arg1: ContactInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1);
            return result;
        }
    }
    async updateDeal(arg0: string, arg1: DealInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeal(arg0, to_candid_DealInput_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeal(arg0, to_candid_DealInput_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTask(arg0: string, arg1: TaskInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_TaskInput_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_TaskInput_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivityType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Deal_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deal): Deal {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Stage_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stage): Stage {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ActivityType]): ActivityType | null {
    return value.length === 0 ? null : from_candid_ActivityType_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    activityType: _ActivityType;
    contactName: string;
    createdAt: bigint;
    description: string;
    dealId: _Id;
    tenantId: _Id;
    occurredAt: bigint;
    companyName: string;
    contactId: _Id;
    dealName: string;
    companyId: _Id;
}): {
    id: Id;
    title: string;
    activityType: ActivityType;
    contactName: string;
    createdAt: bigint;
    description: string;
    dealId: Id;
    tenantId: Id;
    occurredAt: bigint;
    companyName: string;
    contactId: Id;
    dealName: string;
    companyId: Id;
} {
    return {
        id: value.id,
        title: value.title,
        activityType: from_candid_ActivityType_n15(_uploadFile, _downloadFile, value.activityType),
        contactName: value.contactName,
        createdAt: value.createdAt,
        description: value.description,
        dealId: value.dealId,
        tenantId: value.tenantId,
        occurredAt: value.occurredAt,
        companyName: value.companyName,
        contactId: value.contactId,
        dealName: value.dealName,
        companyId: value.companyId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    nextActivityDate: [] | [bigint];
    title: string;
    nextActivityNote: string;
    nextActivityType: [] | [_ActivityType];
    contactName: string;
    value: number;
    createdAt: bigint;
    tags: Array<string>;
    tenantId: _Id;
    updatedAt: bigint;
    stage: _Stage;
    notes: string;
    companyName: string;
    contactId: _Id;
    companyId: _Id;
}): {
    id: Id;
    nextActivityDate?: bigint;
    title: string;
    nextActivityNote: string;
    nextActivityType?: ActivityType;
    contactName: string;
    value: number;
    createdAt: bigint;
    tags: Array<string>;
    tenantId: Id;
    updatedAt: bigint;
    stage: Stage;
    notes: string;
    companyName: string;
    contactId: Id;
    companyId: Id;
} {
    return {
        id: value.id,
        nextActivityDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.nextActivityDate)),
        title: value.title,
        nextActivityNote: value.nextActivityNote,
        nextActivityType: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.nextActivityType)),
        contactName: value.contactName,
        value: value.value,
        createdAt: value.createdAt,
        tags: value.tags,
        tenantId: value.tenantId,
        updatedAt: value.updatedAt,
        stage: from_candid_Stage_n24(_uploadFile, _downloadFile, value.stage),
        notes: value.notes,
        companyName: value.companyName,
        contactId: value.contactId,
        companyId: value.companyId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    contactName: string;
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    dealId: _Id;
    tenantId: _Id;
    contactId: _Id;
    dealName: string;
}): {
    id: Id;
    title: string;
    contactName: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    dealId: Id;
    tenantId: Id;
    contactId: Id;
    dealName: string;
} {
    return {
        id: value.id,
        title: value.title,
        contactName: value.contactName,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        dealId: value.dealId,
        tenantId: value.tenantId,
        contactId: value.contactId,
        dealName: value.dealName
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Email: null;
} | {
    Call: null;
} | {
    Note: null;
} | {
    Meeting: null;
}): ActivityType {
    return "Email" in value ? ActivityType.Email : "Call" in value ? ActivityType.Call : "Note" in value ? ActivityType.Note : "Meeting" in value ? ActivityType.Meeting : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Lead: null;
} | {
    Qualified: null;
} | {
    Proposal: null;
} | {
    ClosedWon: null;
} | {
    ClosedLost: null;
}): Stage {
    return "Lead" in value ? Stage.Lead : "Qualified" in value ? Stage.Qualified : "Proposal" in value ? Stage.Proposal : "ClosedWon" in value ? Stage.ClosedWon : "Negotiation" in value ? Stage.Negotiation : "ClosedLost" in value ? Stage.ClosedLost : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deal>): Array<Deal> {
    return value.map((x)=>from_candid_Deal_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n26(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityInput): _ActivityInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ActivityType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_DealInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealInput): _DealInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_DealNextActivityInput_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealNextActivityInput): _DealNextActivityInput {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Stage_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stage): _Stage {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_TaskInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskInput): _TaskInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contactName: string;
    completed: boolean;
    dueDate?: bigint;
    description: string;
    dealId: Id;
    contactId: Id;
    dealName: string;
}): {
    title: string;
    contactName: string;
    completed: boolean;
    dueDate: [] | [bigint];
    description: string;
    dealId: _Id;
    contactId: _Id;
    dealName: string;
} {
    return {
        title: value.title,
        contactName: value.contactName,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        dealId: value.dealId,
        contactId: value.contactId,
        dealName: value.dealName
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityType?: ActivityType;
    date?: bigint;
    note: string;
}): {
    activityType: [] | [_ActivityType];
    date: [] | [bigint];
    note: string;
} {
    return {
        activityType: value.activityType ? candid_some(to_candid_ActivityType_n5(_uploadFile, _downloadFile, value.activityType)) : candid_none(),
        date: value.date ? candid_some(value.date) : candid_none(),
        note: value.note
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    activityType: ActivityType;
    contactName: string;
    description: string;
    dealId: Id;
    occurredAt: bigint;
    companyName: string;
    contactId: Id;
    dealName: string;
    companyId: Id;
}): {
    title: string;
    activityType: _ActivityType;
    contactName: string;
    description: string;
    dealId: _Id;
    occurredAt: bigint;
    companyName: string;
    contactId: _Id;
    dealName: string;
    companyId: _Id;
} {
    return {
        title: value.title,
        activityType: to_candid_ActivityType_n5(_uploadFile, _downloadFile, value.activityType),
        contactName: value.contactName,
        description: value.description,
        dealId: value.dealId,
        occurredAt: value.occurredAt,
        companyName: value.companyName,
        contactId: value.contactId,
        dealName: value.dealName,
        companyId: value.companyId
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nextActivityDate?: bigint;
    title: string;
    nextActivityNote: string;
    nextActivityType?: ActivityType;
    contactName: string;
    value: number;
    tags: Array<string>;
    stage: Stage;
    notes: string;
    companyName: string;
    contactId: Id;
    companyId: Id;
}): {
    nextActivityDate: [] | [bigint];
    title: string;
    nextActivityNote: string;
    nextActivityType: [] | [_ActivityType];
    contactName: string;
    value: number;
    tags: Array<string>;
    stage: _Stage;
    notes: string;
    companyName: string;
    contactId: _Id;
    companyId: _Id;
} {
    return {
        nextActivityDate: value.nextActivityDate ? candid_some(value.nextActivityDate) : candid_none(),
        title: value.title,
        nextActivityNote: value.nextActivityNote,
        nextActivityType: value.nextActivityType ? candid_some(to_candid_ActivityType_n5(_uploadFile, _downloadFile, value.nextActivityType)) : candid_none(),
        contactName: value.contactName,
        value: value.value,
        tags: value.tags,
        stage: to_candid_Stage_n9(_uploadFile, _downloadFile, value.stage),
        notes: value.notes,
        companyName: value.companyName,
        contactId: value.contactId,
        companyId: value.companyId
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stage): {
    Lead: null;
} | {
    Qualified: null;
} | {
    Proposal: null;
} | {
    ClosedWon: null;
} | {
    ClosedLost: null;
} {
    return value == Stage.Lead ? {
        Lead: null
    } : value == Stage.Qualified ? {
        Qualified: null
    } : value == Stage.Proposal ? {
        Proposal: null
    } : value == Stage.ClosedWon ? {
        ClosedWon: null
    } : value == Stage.Negotiation ? {
        Negotiation: null
    } : value == Stage.ClosedLost ? {
        ClosedLost: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    Email: null;
} | {
    Call: null;
} | {
    Note: null;
} | {
    Meeting: null;
} {
    return value == ActivityType.Email ? {
        Email: null
    } : value == ActivityType.Call ? {
        Call: null
    } : value == ActivityType.Note ? {
        Note: null
    } : value == ActivityType.Meeting ? {
        Meeting: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
